Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(example.py:142187): Gdk-CRITICAL **: 09:12:30.926: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

Loading data...

Training...

Evaluating...
accuracy  0.9833333333333333
classification report...
              precision    recall  f1-score   support

         1.0       0.98      1.00      0.99        50
         2.0       1.00      1.00      1.00        50
         3.0       0.98      0.98      0.98        50
         4.0       0.96      0.98      0.97        50
         5.0       1.00      0.98      0.99        50
         6.0       0.98      0.96      0.97        50

    accuracy                           0.98       300
   macro avg       0.98      0.98      0.98       300
weighted avg       0.98      0.98      0.98       300

